name: This is a github action
run-name: this is the run name
on: [push]
jobs:
  test:
   runs-on: ubuntu-latest
   steps: 
     - name: setup node.js
       uses: actions/setup-nodes@v4
       with: 
         node-version: "21.5.0"
     - run: node --version

